""""category_type"

Revision ID: 34c0cddd73c1
Revises: 38327cbac34f
Create Date: 2026-02-13 16:00:21.096007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c0cddd73c1'
down_revision: Union[str, Sequence[str], None] = '38327cbac34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'type')
    # ### end Alembic commands ###
