"""category type

Revision ID: 38327cbac34f
Revises: 52b94e88ebe1
Create Date: 2026-02-13 15:52:09.462958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38327cbac34f'
down_revision: Union[str, Sequence[str], None] = '52b94e88ebe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
